### ISSUE TITLE
Sign-opt attack not working

### ISSUE THREAD

**Issue by maithal** [cmhcbb/attackbox#10]
Hi,

I was trying to use this attack on MNIST dataset, however, everytime I run the attack it is able to attack only 2 out of 100 images. Is there anything that needs to be changed?

04/26 03:08:22 AM image batch: 100
04/26 03:08:22 AM ==========
04/26 03:08:22 AM clean count:100
04/26 03:08:22 AM acc under attack count:2
04/26 03:08:22 AM avg total queries used:6171451
04/26 03:08:22 AM avg stop queries used:nan
04/26 03:08:22 AM average distortion:1.0405200320482253
04/26 03:08:22 AM robust accuracy rays: nan
04/26 03:08:22 AM robust accuracy: 1.0

python test_attack.py --attack Sign_OPT --dataset MNIST --model 'mnist' --epsilon 0.01 --test_batch_size 1

Please help!

**Comment by cmhcbb** [comment]
Hi,

The acc under attack count means how many examples are still classified as correct. In the above case, 98 of 100 exmamples has been attacked successfully as all the 100 examples are correctly classified.

**Comment by maithal** [comment]
That makes a lot sense. Thanks for the quick response!
