### ISSUE TITLE
Is this the official Code for Sign-OPT?

### ISSUE THREAD

**Issue by Wuziyi616** [cmhcbb/attackbox#4]
Hi! Thank you for opening source this great work! I just want to ask whether **attack/Sign_OPT.py** is the official implementation for the paper [Sign-OPT](https://arxiv.org/abs/1909.10773) published on ICLR'20?

**Comment by Wuziyi616** [comment]
Also, I wonder what's the difference between Sign_OPT, Sign_OPT_lf and Sign_OPT_v2? I'm new in this topic so hope that you can kindly answer me. Thanks!

**Comment by cmhcbb** [comment]
Hi, Yes, it is the official implementation of the ICLR'20 paper.
The Sign_OPT and Sign_OPT_v2 are used in generating the adversarial examples in L2 norm. The v2 is just a slight variance. 
Sign_OPT_lf is used in generating the adversarial examples in L_inf norm. 
It is the code for the results reported in the original paper.

**Comment by Wuziyi616** [comment]
Thank you very much for your quick reply! It helps a lot.
